### ISSUE TITLE
starting when already started aggressively tries 30 times

### ISSUE THREAD

**Issue by jonassmedegaard** [atomicdata-dev/atomic-data-rust#335] opened 2022-03-17 11:46 UTC
If I start the service while it is already running, then it warns and then tries 30 times before failing.

I would expect to immediately fail.

I recommend to only aggressively try *optionally*, e.g. with new option `--persist` (taking optional integer value, default 30).

**Comment by joepio** [comment] 2022-03-18 10:02
I think this is a duplicate of #324, right?

**Comment by jonassmedegaard** [comment] 2022-03-18 11:08
No: Issues are related but different.

One solution fixes them both (never restarting from within application - completely leaving that to systemd or similar external tooling), but other solutions might address only one but not the other (e.g. solving #324 by making auto-start optional).

**Comment by joepio** [comment] 2023-02-21 17:36
Restarting is no longer default - only behind a flag, because #324 was implemented. I think this one is fixed now.

**Closed by joepio** 2023-02-21 17:36 UTC
